### PR TITLE
Add wayland support

### PR DESCRIPTION
**Pull request by fwsmit**
This PR adds wayland support to this utility. There are also a few other minor improvements included:
- Add appname to the notification for allowing to change it's appearance/settings in dunst configuration
- Use default shell instead of bash
- Make sure everything is quoted to prevent globbing

### CODE REVIEW

**Comment by 4lgn** [comment]
This is awesome, thank you very much - I'll merge it in!

**Comment by fwsmit** [comment]
Great. I was also wondering why the notification was made low priority. I think it's better to make it normal priority. What do you think?

**Comment by 4lgn** [comment]
I actually reckon that was just a personal choice because of the differing colors on my system - but yeah, normal priority would make more sense.

**Comment by fwsmit** [comment]
I made a PR about it #2

**Pull request merged**
